### ISSUE TITLE
Broken Display and Interactivity

### ISSUE THREAD

**Issue by cb109** [HordeSoftware-co/pyflowgraph#1]
Hi, I tried to run your examples within Tests/ using PySide 1.2.4 (Windows 7 x64, Python 2.7.10 x64). The widget opens and I can see some sort of node graph, but its broken both in what it shows and also in that I cannot change anything. Any ideas why this may happen? Are you maybe using a different PySide version?

![](http://i.imgur.com/yZ7Z2rF.png)

**Comment by EricTRocks** [comment]
I recently saw this with Kraken which is built on top of Pyflow Graph and I had to use PySide 1.2.2

**Comment by cb109** [comment]
Thanks, I can run the examples now! I'll suggest making this a python package with a setup.py/requirements.txt to specify the dependency version and simplify the installation.
