### ISSUE TITLE
Make it a package

### ISSUE THREAD

**Issue by cb109** [HordeSoftware-co/pyflowgraph#2]
I think this project would benefit from a default python package setup. It would enable it to be installed via well known methods (e.g. pip or easy_install) automatically handling its dependencies. The packages it needs could be pinned to specific versions (e.g. PySide==1.2.2, since using 1.2.4 does not work atm).

I can do this if you like and send a pull request with a minimal setup.py.

**Comment by EricTRocks** [comment]
@cb109 I've done this work and pyflowgraph is now available via PyPI:
[https://pypi.python.org/pypi/pyflowgraph/0.0.1](https://pypi.python.org/pypi/pyflowgraph/0.0.1)

**Comment by cb109** [comment]
:+1:
